# MAL Determin shapes


## Problem description
TODO: hvilket problem førsøger i at løse med ML?


Our project is about detecting and clasifying four different shapes. The shapes we want to detect is Squares, Triangels, Circles and Stars. 



## The dataset
TODO: hvilke data arbejder i med, hvilke features, hvor stammer det fra osv. (tag udgangspunkt i jeres aflevering "L03 Beskrivelse af eget slutprojekt" i O1).


### Loading the Shape dataset

In [20]:
import cv2
import numpy as np
import glob
import os
import matplotlib
import matplotlib.pyplot as plt

In [6]:
#TODO load the dataset:
import sys,os
from time import time
sys.path.append(os.path.expanduser('ProjectFunctions'))
from ProjectFunctions import LoadShapes as LS


#def getStar():
#    imageList = glob.glob('DataSet/star/*.png')
#    x  = np.array([np.array(Image.open(fname)) for fname in imageList])
#    return x

start = time()

star = LS.getStar()
print("Star: ", star.shape)

circle = LS.getCircle()
print("Circle: ", circle.shape)

triangle= LS.getTriangle()
print("Triangle: ", triangle.shape)

square = LS.getSquare()
print("Square: ", square.shape)

t = time()-start
print(f"OK, Load time={t:0.1f}")

Star:  (3765, 200, 200)
Circle:  (3720, 200, 200)
Triangle:  (3720, 200, 200)
Square:  (3765, 200, 200)
OK, Load time=13.2


### Creating the dataset
Since our data is pictures in different folders we need to join them into our data X and label the data with y.

In [7]:
# Resixing the data:
size = circle.shape[0]    # The smallest size of the dataset
star = star[:size]
circle = circle[:size]
square = square[:size]
triangle = triangle[:size]

# Joining the data in arrays:
X = np.concatenate((star, circle, square, triangle))
y = np.concatenate((LS.get_yStar(), LS.get_yTriangle(), LS.get_yCircle(), LS.get_ySquare()))


In [8]:
import pylab as pult
from PIL import Image
import cv2
# pult.imshow(X[8+3765])

print("Star",star)
print("x",X)

imStar = Image.fromarray(X[8])
display(imCircle)

imCircle = Image.fromarray(circle[8+3720])
display(imCircle)

imSquare = Image.fromarray(circle[8+(2*3720)])
display(imCircle)

imTriangle = Image.fromarray(circle[8+(3*3720)])
display(imCircle)

Star [[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 ...

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 

NameError: name 'imCircle' is not defined

In [22]:
from scipy import misc
import cv2
import glob

for image_path in glob.glob('DataSet/star/*.png'):
    image = cv2.imread(image_path)


In [26]:
#print(image)

cv2.imshow('image[0]', image[0]) 

### Categorizing the data
Since our data comes as 4 folders with pictures.

### Preparing the date for neural networks

We need to change the pixel data from the range 0 - 255 to a value between 0 and 1. This is because the neurons works with step functions (in the range from 0 and 1) in the activation function step and for our data to be prossesed corrrectly in a neural network ve need to feed the network with data in the same range. 

In [ ]:
X1=X/255

### Splitting the dataset 

In [ ]:
#TODO split the dataset:



## Preprossing
TODO: descripe what we think has been done to our data in the preprossing prosses.

### Running our own preprossing:

In [ ]:
#TODO: try ro run a known CNN on the data and see what happens.

## ML-Algorithms
TODO: beskriv f.eks.
* hvilken grundliggende ML algoritmeklasse(r) valgte i (supervised/unsupervised, regression/classifikation)?
* hvilke kriterier lå til grund for jeres model selection?
* hvorfor er jeres valgtealgoritme god til netop jeres dataset?
* hvad er fordele og ulemper ved den (eller de) valgte algoritme(r), f.eks. kompleksitet?

### Classifying the data

In [ ]:
#Todo run algorithms:

## ML pipeline:
TODO: Beskrivelse af hvordan i splitter data i train-test set, preprocessere, træner og tester.

## Performance metrics:
TODO: beskrivelse af, hvordan i måler 'effektiviteten' af jeres træning og test.

## Optimeringer og forbedringer:
TODO:  hvordan har i forbedret jeres system via optimeringsparametre (optimizers, regulizers) eller afsøgning af hyperparameterrummet? 

## Under- og overfitting: 
TODO: hvordan sørger i for, at jeres system ikke under- eller overfitter på jeres data?

## Diskussion (ikke et krav)
TODO: Diskuter hvad man ellers kunne gøre med dataen, mere data? præprossesering.

## Konklussion
TODO: Konklussionen på opgaven